### ISSUE TITLE
What's the story with old nightly builds?

### ISSUE THREAD

**Issue by zvonimir** [Z3Prover/bin#1]
Hi guys,

So I am curious what is your long term strategy when it comes to storing old nightly builds?

In particular, our project (SMACK) relies on the following Z3 build:
`f139669240f613e86cac199e518dbc3541cf16bd`

The respective binaries were moved around a couple of times, and most recently they resided here:
`https://github.com/Z3Prover/bin-old/blob/f139669240f613e86cac199e518dbc3541cf16bd/z3-4.4.0.1abeb825a35a-x64-ubuntu-14.04.zip?raw=true`

But now this link is broken too.

I would appreciate if you could share your long-term plans for storing Z3 nightly (Linux) builds. At this point we are thinking about hosting versions that we need on our end, but ideally we would like to avoid that.

Thanks!

**Comment by wintersteiger** [comment]
Hi Zvonimir,

There is no long-term strategy. We were taking up too much space and all local clones of the bin repository grew huge too, with no benefit to either ourselves or any users. At the moment the infrastructure is set up to throw away all history of the bin repository and then to upload the latest files, so there will only ever be the most recent successful build. If for some reason you need new binaries every day, you can download and store them at your end. They are updated at most once a day (with rare exceptions), so that can easily be automated.

Of course, the source history remains untouched, so you can always compile any old version on your end.

**Comment by zvonimir** [comment]
Quick follow up question: do you maybe provide Linux binaries for official releases?

**Comment by wintersteiger** [comment]
Up until now we haven't, but we can discuss that. So far we never needed that, because most Linux users have no problem compiling their own. May I ask where your need for binaries stems from?

**Comment by zvonimir** [comment]
Sure, let me share the long version of the background story.

So, in our SMACK project, for a long time our automatic build script would compile Z3 from sources, which was fine for the most part. Then, maybe a year ago, we switched to using vagrant for easy cross-platform portability. Now, you just do `vagrant up` and our script installs all dependencies needed for running SMACK (including Z3), and you are completely ready to go in several minutes. This nice "several minutes" vagrant boot time relies on the fact that we switched to using Z3 binaries instead of building Z3 from sources, which takes a long time, especially on slower machines. So without pre-compiled binaries, our users who would like to try out SMACK have to wait for a long time for Z3 to be compiled - maybe even half an hour if I remember correctly. And given that we don't have to update Z3 version that often, pulling binaries from somewhere makes sense for SMACK.

I hope this clarifies it. Our main question at this point is whether we should switch to hosting Z3 binaries on our end or not, since that would certainly be a feasible solution.

Thanks for your help.

**Comment by zvonimir** [comment]
Btw, I should finally add that for us a good enough solution would most likely be if you would just provide persistent Linux binaries for your official releases. We don't really need a complete history of all nightly builds.

**Comment by zvonimir** [comment]
I guess I do have one more thing to add.
I would appreciate your feedback/thoughts/proposed solution on this sooner rather than later if possible. We applied with SMACK for ASE tool demos, and currently our build script is broken due to this issue. I would really like to properly fix this over the weekend so that our users and potential reviewers do not get affected.
Thanks!

**Comment by wintersteiger** [comment]
Yes, releases should definitely be good enough for that. I can't guarantee to get those uploaded this weekend though, so prepare for a fallback. 

You are aware of the license change though, right? Z3 now comes under the MIT license, therefore you can distribute your preferred version with SMACK. (At least in source form, but I think this applies equally to the binaries.)

**Comment by wintersteiger** [comment]
Linux release binaries are now available [here](https://github.com/Z3Prover/bin/tree/master/releases) and [here](https://github.com/Z3Prover/z3/releases/tag/z3-4.4.0).

**Comment by zvonimir** [comment]
This is exactly what we needed! Thanks a lot for helping out!

**Comment by wintersteiger** [comment]
Great! I'll close this issue as resolved then.
