### ISSUE TITLE
z3py not timeout-ing

### ISSUE THREAD

**Issue by fuxiang-chen** [Z3Prover/bin#4]
When using z3py with set("timeout", 600) where 600 is the ms to timeout, it is not timing out as expected.

There's no error and the process will just keep running.

Using latest release for ubuntu x64 4.5.0 release. 

**_My environment_**: 
_Linux version 4.2.0-27-generic (buildd@lcy01-23) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #32~14.04.1-Ubuntu SMP_

A bug?

**Comment by wintersteiger** [comment]
This issue tracker is just for issue with our nightly distribution files, please use the main [Z3 issue tracker](https://github.com/Z3Prover/z3/issues). And yes, we know that such issues exist, but we need example inputs to figure out where and why they happen.
