### ISSUE TITLE
Windows build not updating in the nightly

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/bin#5]
@wintersteiger 

Looks like the last successful windows build is from two days ago; though according to commit logs it's compiling fine on Windows.

Is there a reason the windows nightly's stopped working?

**Comment by wintersteiger** [comment]
Sorry, happens. The binaries were correctly built, but the force-pushes from different VMs overlapped and overwrote each other. I'll bump the Windows builds to a later time, but this will continue to happen from time to time.
