### ISSUE TITLE
linux builds not update anymore?

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/bin#6]
The linux nightly builds are 27 days old, while the windows nightly builds are of today.
![image](https://user-images.githubusercontent.com/18348654/50843780-a0190980-1369-11e9-858c-4307e4e8fb40.png)
Are the linux nightly builds failing, or is something else wrong?

**Comment by wintersteiger** [comment]
They were disabled, I re-enabled them just now. @NikolajBjorner what are your plans for the nightly binaries, are those generated by the new CI infrastructure and perhaps checked in elsewhere?

**Comment by NikolajBjorner** [comment]
The nightly builds have moved to Z3Prover/z3 under "Releases". They are tagged as "Nightly"
