### ISSUE TITLE
When is the new nightly build scheduled?

### ISSUE THREAD

**Issue by shiatsumat** [Z3Prover/bin#9]
Now that [Z3 4.8.5 is released here](https://github.com/Z3Prover/z3/releases), the nightly build here is the same with the current version.
Since the bug fix of https://github.com/Z3Prover/z3/issues/231 (which missed Z3 4.8.5) is crucial for me, I am looking forward to the release of the new nightly build for Z3 4.8.6 (for easier distribution of Z3).

**Comment by wintersteiger** [comment]
There is no schedule and there are frequent failures and outages. If you depend on the latest code, I recommend compiling your preferred version yourself.

**Comment by NikolajBjorner** [comment]
The nightly builds have moved to Z3Prover/z3 under "Releases". They are tagged as "Nightly"
